//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWsurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyRecord
    {
        public int SurveyRecordSn { get; set; }
        public int SurveyQuestionSn { get; set; }
        public string OptionValue { get; set; }
        public string TxtValue { get; set; }
        public int SRootSn { get; set; }
    
        public virtual SurveyQuestion SurveyQuestion { get; set; }
        public virtual SurveyRecordRoot SurveyRecordRoot { get; set; }
    }
}
