//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWsurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyRecordRoot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyRecordRoot()
        {
            this.SurveyRecord = new HashSet<SurveyRecord>();
        }
    
        public int SRootSn { get; set; }
        public string UserType { get; set; }
        public string UserID { get; set; }
        public System.DateTime InsTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyRecord> SurveyRecord { get; set; }
    }
}
