//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWsurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyQuestion()
        {
            this.SurveyOption = new HashSet<SurveyOption>();
            this.SurveyRecord = new HashSet<SurveyRecord>();
        }
    
        public int SurveyQuestionSn { get; set; }
        public int SurveyGroupSn { get; set; }
        public byte QuestionOrder { get; set; }
        public string Question { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public bool MustKeyin { get; set; }
    
        public virtual SurveyGroup SurveyGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyOption> SurveyOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyRecord> SurveyRecord { get; set; }
    }
}
